name: Daily Poetry Blog Generator

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git operations

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai

    - name: Generate blog post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_blog.py

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit and push if changed
      run: |
        git add _posts/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add daily poetry post for $(date +%Y-%m-%d)" && git push)